# Generated by Django 4.2.1 on 2023-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
