# Generated by Django 4.2.1 on 2023-08-10 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField()),
                ('other_subject', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('C++', 'C++'), ('HTML,CSS', 'HTML.CSS'), ('REACT', 'REACT'), ('COMPUTER NETWORKS', 'COMPUTER NETWORKS'), ('DATABASES', 'DATABASES'), ('CLOUD COMPUTING', 'CLOUD COMPUTING')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
