# Generated by Django 4.2.1 on 2023-08-30 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('module', models.CharField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('HTML,CSS,JS', 'Html,css,js'), ('REACT', 'REACT'), ('CN', 'Comupter Networks'), ('DB', 'Databases'), ('C++', 'C++'), ('None', 'None')], max_length=50)),
                ('module2', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
